pimlicolabs/alto

test/run-spec-tests.sh

Fix: test script fix

---

packages/executor/src/senderManager.ts
packages/types/src/contracts/CallEngine.ts
packages/types/src/index.ts

Changes
- Added ABI for CallEngine
- For Linea, make refill payments in a single transaction using multicall call engine

feat: multicall refills for linea

---

packages/rpc/src/vatidation/tracer.ts

chore: fix typos

---

packages/cli/src/handler.ts
packages/mempool/src/mempool.ts

Display processing operations count on shutdown

Add dumpProcessing() method to Mempool

---

packages/executor/src/executor.ts
packages/executor/src/executorManager.ts
packages/utils/src/metrics.ts

- count failed bundles
- count failed ops
- count filtered ops
- some logging improvements

Observability improvements

---

packages/executor/src/executorManager.ts
packages/utils/src/metrics.ts

- count replaced transactions by reason/status
- count rejected/failed ops

Add more metrics for tracking ops and txs statuses

---

src/cli/handler.ts
src/entrypoint-0.6/rpc/validation/UnsafeValidator.ts

Revert "Fix Gas Estimation Issues"

---

src/cli/handler.ts
src/entrypoint-0.6/executor/executorManager.ts
src/entrypoint-0.7/executor/executorManager.ts
src/entrypoint-0.7/types/schemas.ts
src/utils/metrics.ts

- Use a separate metric for counting resubmissions (I believe this approach is more appropriate)
- Add entrypoint version to the metrics labels
- Adjust the log entry to align with the same log in entrypoint version 0.6

Improve metrics a bit

---

src/cli/config/bundler.ts
src/cli/config/options.ts
src/entrypoint-0.7/cli/setup-entrypoint-point-seven.ts
src/entrypoint-0.7/rpc/EntryPointSimulations.ts
src/entrypoint-0.7/rpc/validation/SafeValidator.ts
src/entrypoint-0.7/rpc/validation/UnsafeValidator.ts

This reverts commit 81254593dafa9fe0e3bde6f5465bba54d2868edd.

Revert "Change to entryPointSimulationsAddressTemp for no downtime"

---

src/rpc/rpcHandler.ts
src/types/schemas.ts

related to [this permissionless pr](https://github.com/pimlicolabs/permissionless.js/pull/181)

add missing fields to eth_getUserOperationReceipt

---

src/cli/config/bundler.ts
src/cli/config/options.ts
src/cli/setupServer.ts
src/rpc/rpcHandler.ts

Include v0.7 paymaster gas limit multiplier

---

src/rpc/rpcHandler.ts

Celo is at 32M gas too - https://forum.celo.org/t/proposal-to-increase-block-gas-limit-to-32m-gas/6431/8

remove celo specific callGasLimit

---

scripts/localDeployer/index.ts

this helps when running on anvil without automine

local deployer waits for transactions

---

src/executor/executorManager.ts

- Fix metrics when userOperation is frontran onchain
- remove from submitted mempool + increment/decrement the metric based on weather it was frontran

fix userOperationsOnChain metric

---

src/rpc/rpcHandler.ts

add log to detect check if missing balance override reverts

---

.changeset/purple-drinks-hide.md
package.json
src/cli/alto.ts
src/package.json

Reference: https://github.com/pimlicolabs/alto/pull/431

ship alto bin in npm

---

src/rpc/estimation/gasEstimationHandler.ts
src/rpc/rpcHandler.ts
src/rpc/validation/UnsafeValidator.ts
src/types/interfaces.ts

Revert "add deposit override during estimations"

---

src/executor/utils.ts
src/rpc/estimation/gasEstimationsV06.ts
src/rpc/estimation/gasEstimationsV07.ts
src/rpc/methods/eth_estimateUserOperationGas.ts
src/rpc/methods/eth_sendUserOperation.ts
src/rpc/methods/pimlico_experimental_estimateUserOperationGas7702.ts
src/rpc/methods/pimlico_experimental_sendUserOperation7702.ts
src/rpc/rpcHandler.ts
src/rpc/validation/SafeValidator.ts
src/rpc/validation/tracer.ts
src/types/schemas.ts
src/utils/helpers.ts
src/utils/validation.ts

This reverts commit 672f35b8869931cbb98e69b264d23abca4983735.

Revert "Revert "Make 7702 compliant with entryPoint 0.8 specs""

---

src/handlers/gasPriceManager.ts

This reverts commit 2c32f13fa36f982131211dfbcebe78c4761f0a8e.

Revert "fix uncaught error"

---

src/executor/executor.ts

This reverts commit 0f81fe6498043fc4e452676cb2e9928ea0db80c6.

Revert "estimate gas with state overrides for 7702"

---

src/rpc/methods/eth_sendUserOperation.ts
src/rpc/methods/pimlico_sendUserOperationNow.ts
src/types/utils.ts

- Throw with InvalidFields error code instead of throwing internal error

throw with error code if userOp fails preMempool checks
